### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by petr1valenta** [SpiritsCreations/FiveM-Lore-Friendly-Car-Pack#2]
[    114453] [b3095_DumpServ]                 4512/ gta-streaming-five.dll!GetStreamingModuleWithValidate<1> (0x33)
[    114453] [b3095_DumpServ]                 4512/ An error at gta-streaming-five.dll!GetStreamingModuleWithValidate<1> (0x33) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.
[    114453] [b3095_DumpServ]                 4512/ Stack trace:
[    114453] [b3095_DumpServ]                 4512/   gta-streaming-five.dll!GetStreamingModuleWithValidate<1> (0x33) (<A HREF="https://sourcegraph.com/github.com/citizenfx/fivem/-/blob/beta/fivem/code/components/gta-streaming-five/src/StreamingFreeTests.cpp?L124">StreamingFreeTests.cpp:124</A>)
[    114453] [b3095_DumpServ]                 4512/   GTA5_b3095.exe!sub_141647D48 (0x19c)
[    114453] [b3095_DumpServ]                 4512/   GTA5_b3095.exe!sub_141647D48 (0x305)
[    114453] [b3095_DumpServ]                 4512/   GTA5_b3095.exe!sub_141647D48 (0x305)
[    114453] [b3095_DumpServ]                 4512/   GTA5_b3095.exe!sub_141647D48 (0x305)
[    114453] [b3095_DumpServ]                 4512/   GTA5_b3095.exe!sub_141647D48 (0x305)
[    114453] [b3095_DumpServ]                 4512/   GTA5_b3095.exe!sub_141647D48 (0x305)
[    114453] [b3095_DumpServ]                 4512/ 
[    119063] [b3095_DumpServ]                 4512/ Crash report service returned si-be6d3917e1314cab9f8388e5facacc46

**Comment by SpiritsCreations** [comment]
Upon trying to replicate the issue, I can't recreate the issue, I know the issue that would tie in to the Lore Friendly Pack which I can replicate multiple times!

I would ask if there is anything further up within your CitizenFX_log file that would point towards this Vehicle Pack causing the issue, like wise does the issue only happen when it is enabled, or is it something else that is clashing with the Vehicle Pack to cause a Server Crash?

**Comment by petr1valenta** [comment]
It only happens when the pack is on the server, and it always crashes at the end of the loading screen

**Comment by Error420Unknown** [comment]
My friend has been receiving same issue.

I looked at the crash log and its the rh4elegy or elegyrh6 that's crashing it.

**Comment by SpiritsCreations** [comment]
Updated to Version 1.1 for the Vehicle Pack, may fix your issue as I begin working on the next installment for this vehicle pack!

Please let me know of any more issues!
Sorry for a late response!
